[package]
name = "bitcoin-circuit"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { path="../../risc0/risc0/build" ,default-features = false}

[package.metadata.risc0]
methods = ["guest"]
